---
* *** 원본 소스는 홍콩과기대 김성훈 교수님의  [Github link](https://github.com/hunkim/DeepLearningZeroToAll)를 참조하세요 ***     
* *** Watson studio notebook 에서 작업 가능하도록 수정하였으며***
* *** 한글로 설명된 부분은 제가 스터디 하면서 이해한 내용을 추가한 것입니다. ***
---

# Lab 7-2 Linear regression without min-max
* ***여기서는 feature (X) 들간의 data 크기 편차가 너무 커서 learning 이 제대로 안되는 예시입니다***
* ***data 표준화 작업이 필요합니다.   세번째 칼럼 값이 상대적으로 너무 큽니다.***

In [16]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [4]:
from scipy import stats
print(stats.describe(x_data))
print(stats.describe(y_data))

DescribeResult(nobs=8, minmax=(array([8.09510010e+02, 8.15250000e+02, 9.08100000e+05, 8.04539978e+02]), array([8.28659973e+02, 8.33450012e+02, 1.82810000e+06, 8.28349976e+02])), mean=array([8.18397499e+02, 8.23098625e+02, 1.25810000e+06, 8.16658119e+02]), variance=array([3.71308274e+01, 3.44591661e+01, 8.51428571e+10, 5.23282265e+01]), skewness=array([ 0.11346773,  0.35788876,  0.80290717, -0.14738366]), kurtosis=array([-0.65064498, -0.57607135, -0.14880501, -0.42692814]))
DescribeResult(nobs=8, minmax=(array([809.559998]), array([831.659973])), mean=array([820.7237395]), variance=array([52.15404165]), skewness=array([-0.00237535]), kurtosis=array([-0.87647491]))


In [14]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10)
train = optimizer.minimize(cost)

* ***혹시나 해서 Learning rate 를 조정해보지만 결과는 동일하네요***

In [15]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 5 == 0:
        print(step, "Cost: ", cost_val)
print("Prediction ---\n", hy_val)

0 Cost:  5940297000000.0
5 Cost:  inf
10 Cost:  inf
15 Cost:  nan
20 Cost:  nan
25 Cost:  nan
30 Cost:  nan
35 Cost:  nan
40 Cost:  nan
45 Cost:  nan
50 Cost:  nan
55 Cost:  nan
60 Cost:  nan
65 Cost:  nan
70 Cost:  nan
75 Cost:  nan
80 Cost:  nan
85 Cost:  nan
90 Cost:  nan
95 Cost:  nan
100 Cost:  nan
Prediction ---
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


* ***cost 값이 무한대로 발산해버립니다.***

In [ ]:
'''
0 Cost:  2.45533e+12
Prediction:
 [[-1104436.375]
 [-2224342.75 ]
 [-1749606.75 ]
 [-1226179.375]
 [-1445287.125]
 [-1457459.5  ]
 [-1335740.5  ]
 [-1700924.625]]
1 Cost:  2.69762e+27
Prediction:
 [[  3.66371490e+13]
 [  7.37543360e+13]
 [  5.80198785e+13]
 [  4.06716290e+13]
 [  4.79336847e+13]
 [  4.83371348e+13]
 [  4.43026590e+13]
 [  5.64060907e+13]]
2 Cost:  inf
Prediction:
 [[ -1.21438790e+21]
 [ -2.44468702e+21]
 [ -1.92314724e+21]
 [ -1.34811610e+21]
 [ -1.58882674e+21]
 [ -1.60219962e+21]
 [ -1.46847142e+21]
 [ -1.86965602e+21]]
3 Cost:  inf
Prediction:
 [[  4.02525216e+28]
 [  8.10324465e+28]
 [  6.37453079e+28]
 [  4.46851237e+28]
 [  5.26638074e+28]
 [  5.31070676e+28]
 [  4.86744608e+28]
 [  6.19722623e+28]]
4 Cost:  inf
Prediction:
 [[ -1.33422428e+36]
 [ -2.68593010e+36]
 [ -2.11292430e+36]
 [ -1.48114879e+36]
 [ -1.74561303e+36]
 [ -1.76030542e+36]
 [ -1.61338091e+36]
 [ -2.05415459e+36]]
5 Cost:  inf
Prediction:
 [[ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]]
6 Cost:  nan
Prediction:
 [[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]
'''