---
* *** 원본 소스는 홍콩과기대 김성훈 교수님의  [Github link](https://github.com/hunkim/DeepLearningZeroToAll)를 참조하세요 ***     
* *** Watson studio notebook 에서 작업 가능하도록 수정하였으며***
* *** 한글로 설명된 부분은 제가 스터디 하면서 이해한 내용을 추가한 것입니다. ***
---

# Lab 4 Multi-variable linear regression with Data asset
* ***input 을 화일에서 받습니다.***
* ***numpy 읽어들이고, x, y 데이터를 분리합니다.  나중에 learning step 에서 input 으로 넣습니다.***
* ***insert to code 하면 pandas dataframe 밖에 없습니다. ***
* ***여기서 기존 소스는 numpy 를 이용하므로, panda to numpy 변환이 필요합니다.***

In [27]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

## xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
## 아래 source 로 대체합니다. by  "insert to code"

In [28]:

import sys
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_ace6f71a1b9946cbb684ca0d9e6c34c0 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='XXBNCWwO4mooXZRHuqZ71nRmyIlQt8ca3ZWN8pOo56X69DX',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_ace6f71a1b9946cbb684ca0d9e6c34c0.get_object(Bucket='tensorflowlabwithwatsonstudio-donotdelete-pr-neiwaip4a29fcg',Key='data-01-test-score.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body,header=None)

### pandas to numpy
xy = df.values



* ***잘라내기 신공, 별건 아니지만 ^^***
* ***단, 여기서 row 수를 정확하게 모르니, 일단은 ' : ' 전체, 뒤에 shape 에서  None 으로 지정하는 겁니다.***

In [29]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73  80  75]
 [ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]] 25
(25, 1) [[152]
 [185]
 [180]
 [196]
 [142]
 [101]
 [149]
 [115]
 [175]
 [164]
 [141]
 [141]
 [184]
 [152]
 [148]
 [192]
 [147]
 [183]
 [177]
 [159]
 [177]
 [175]
 [175]
 [149]
 [192]]


* ***shape 선언에서 None 으로 matrix 지정하는 것만 다르고 나머지는 동일합니다.***

In [30]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

* ***Learning ***

In [31]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  8013.9 
Prediction:
 [[ 74.1805954 ]
 [ 80.63321686]
 [ 83.98022461]
 [ 91.3227005 ]
 [ 59.21071243]
 [ 41.89090729]
 [ 70.11859131]
 [ 54.8239975 ]
 [ 72.92267609]
 [ 66.10010529]
 [ 65.14825439]
 [ 60.24366379]
 [ 86.90501404]
 [ 71.78623199]
 [ 69.10598755]
 [ 82.41497803]
 [ 65.88251495]
 [ 86.28957367]
 [ 84.18405914]
 [ 76.09278107]
 [ 81.27962494]
 [ 75.88126373]
 [ 78.24948883]
 [ 75.09364319]
 [ 85.10977936]]
100 Cost:  24.4822 
Prediction:
 [[ 158.00280762]
 [ 181.74298096]
 [ 183.41183472]
 [ 199.68835449]
 [ 136.35003662]
 [  98.92388916]
 [ 151.2467041 ]
 [ 114.97437286]
 [ 167.59532166]
 [ 153.99279785]
 [ 143.34011841]
 [ 137.5322876 ]
 [ 189.55923462]
 [ 157.03633118]
 [ 150.66976929]
 [ 185.05744934]
 [ 147.09121704]
 [ 183.6157074 ]
 [ 181.98199463]
 [ 163.57327271]
 [ 176.43994141]
 [ 170.78768921]
 [ 168.92460632]
 [ 159.43598938]
 [ 189.80511475]]
200 Cost:  22.976 
Prediction:
 [[ 157.79986572]
 [ 181.84764099]
 [ 183.32929993]
 [ 199.67205811]
 [ 136.455

* ***새로운 input 값을 넣고 예측해보기 ***

In [32]:
# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[ 175.88304138]]
Other scores will be  [[ 177.93075562]
 [ 180.93258667]]
